### ISSUE TITLE
Object #<Object> has no method 'spawnSync'

### ISSUE THREAD

**Issue by arj03** [clehner/git-ssb-web#1]
I just tried starting git-ssb-web after installing it and I get the following error:

```
/home/arj/.nvm/versions/node/v5.9.1/lib/node_modules/git-ssb-web/server.js:6
in process.env ? process.env.ssb_appname : require('child_process').spawnSync(
                                                                    ^
TypeError: Object #<Object> has no method 'spawnSync'
    at Object.<anonymous> (/home/arj/.nvm/versions/node/v5.9.1/lib/node_modules/git-ssb-web/server.js:6:97)

```

As you can see I'm running node 5.9.1 but have multiple installed. I'm a complete node newbie, but changing the following at the top of server.js makes the program work for me:

```
#!/bin/sh
':' //; exec "$(command -v nodejs || command -v node)" "$0" "$@"
```

To:

`#!/usr/bin/env node
`

**Comment by clehner** [comment]
Do you have a `nodejs` installed also? If so then that gets used in the combined shebang

**Comment by arj03** [comment]
I do, but that is version 0.10.25 :scream:

**Comment by clehner** [comment]
Ok, I'll update the shebang to prefer `node` over `nodejs`, since `nodejs` is likely to be an older version at this point.
